name: CreativeTools
version: 1.0.0
depend: [Libraries]
author: Stargeyt iTrooz_
main: fr.entasia.creativetools.Main
api-version: '1.14'
commands:
  creatools:
    aliases: [creativetools]

  money:
    aliases: [coins]

  eco:
    aliases: [economy, economie]

  spawn:
    aliases: [sp, spa]

  menu:
    aliases: plotmenu

  cosmetiques:
    aliases: [cosm,cosmetique,pet,pets,particules]